from LLMAgent import LLMAgent


class Scorer:
    def __init__(self, mode='score'):
        self.agent = LLMAgent(
            model_name="Qwen2.5-72B-Instruct",
            api_key="EMPTY",
            base_url="http://localhost:8000/v1"
        )
        prompt = ''
        if mode == 'score':
            prompt = """You are a fair and impartial judge for a D&D game content.
                The main character in the game is James, Male, 22, Human.
                He's in a game defined by the keywords "AI, nuclear war, wastelands, high-tech".
    
                You will be given a number of messages that are generated by the DM.
                Upon each message, you shall give a score based on the quality of the message.
                The score shall comprise of the following 5 categories:
                1. Grammar: The message should be grammatically correct without too many format errors.
                2. Coherence: The message should be coherent and make sense.
                3. Creativity: The message should be creative and interesting.
                4. Relevance: The message should be relevant to the context.
                5. Engagement: The message should be engaging and immersive.
    
                You shall give a score from 1 to 5 for each category. 1 being the lowest and 5 being the highest.
                You can be quite harsh with your scoring, but remember to be consistent and fair.
                You need only score the most recent message.
                """
        elif mode == 'compare':
            prompt = """You are a fair and impartial judge for a D&D game content.
                The main character in the game is James, Male, 22, Human.
                He's in a game defined by the keywords "AI, nuclear war, wastelands, high-tech".

                You will be given a number of messages that are generated by two DMs.
                You shall judge which DM is better based on the quality of the message.
                You may judge the messages based on the following 5 categories:
                1. Grammar: The message should be grammatically correct without too many format errors.
                2. Coherence: The message should be coherent and make sense.
                3. Creativity: The message should be creative and interesting.
                4. Relevance: The message should be relevant to the context.
                5. Engagement: The message should be engaging and immersive.
                
                You can be quite harsh with your scoring, but remember to be consistent and fair.
                You need only judge the most recent message from each DM.
                Finally, output which one of the DMs is better. You can not give a tie.
                """
        self.messages = [
            {"role": "system", "content": prompt},
            {"role": "assistant", "content": "Got it!"},
        ]

    def score(self, message):
        # print("Scoring message: "+ message)
        self.messages += [{"role": "user", "content": message}]
        return self.agent.run_basic_inference(self.messages)

    def compare(self, message1, message2):
        message = f"""
        The first DM says: {message1},
        The second DM says: {message2}.
        """
        self.messages += [{"role": "user", "content": message}]
        return self.agent.run_basic_inference(self.messages)


# scorer = Scorer('score')
#
# with open("dnd-storytelling-game-main/Generations/Kimi - moonshot.txt", encoding='utf-8') as f:
#     text = f.read()
#     history = text.split("\n\n")
#
#     history = [message for message in history if
#                not (message.startswith("Choice") or message.startswith("Reward") or message.startswith("Keywords"))]
#     for message in history:
#         print(scorer.score(message), end="\n\n")

scorer = Scorer('compare')

with open("dnd-storytelling-game-main/Generations/Qwen turbo.txt", encoding='utf-8') as f:
    text1 = f.read()
    history1 = text1.split("\n\n")

    history1 = [message for message in history1 if
                not (message.startswith("Choice") or message.startswith("Reward") or message.startswith("Keywords"))]

with open("dnd-storytelling-game-main/Generations/Deepseek chat.txt", encoding='utf-8') as f:
    text2 = f.read()
    history2 = text2.split("\n\n")

    history2 = [message for message in history2 if
                not (message.startswith("Choice") or message.startswith("Reward") or message.startswith("Keywords"))]

for i in range(min(len(history1), len(history2))):
    print(scorer.compare(history1[i], history2[i]), end="\n\n")